export enum ERROR_TYPES {
  UNKNOWN_ERROR,
  VERSION_NOT_PROVIDED,
  INTERNAL_SERVER_ERROR,
  HTTP_ERROR,
  RETRY_QUERY,
  WRONG_PARAMS_ERROR,
  NOT_FOUND,
  MICROSERVICE_PROTOCOL_ERROR,
  ACCESS_DENIED,
  UNAUTHORIZED,
  I18nValidationException,
}
